#!/bin/bash

tmux new -s cardano -d

#creating windows
tmux split-window -h -t cardano
tmux select-pane -t 0

tmux split-window -v -t cardano
tmux select-pane -t 2
tmux split-window -v -t cardano

#core node
tmux select-pane -t 0
tmux send-keys "../node134/cardano-cli query tip --mainnet" C-m

#system info
tmux select-pane -t 1
tmux send-keys 'neofetch' C-m

#relay node
tmux select-pane -t 2
tmux send-keys "cardano-cli query tip --mainnet" C-m

#system performance
tmux select-pane -t 3
tmux send-keys 'htop' C-m


tmux a -t cardano
